### ISSUE TITLE
natlinkconfig_cli.exe and natlinkconfig_gui.exe

### ISSUE THREAD

**Issue by Voxellence** [dictation-toolbox/natlinkcore#25]
I've installed the latest pre-release of NatLink, 5.3.4, which I downloaded from the releases page.

When I run natlinkconfig_cli.exe I get the following:
```
Traceback (most recent call last):
  File "C:\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python310-32\Scripts\natlinkconfig_cli.exe\__main__.py", line 4, in <module>
  File "C:\Python\Python310-32\lib\site-packages\natlinkcore\configure\natlinkconfig_cli.py", line 8, in <module>
    from natlinkcore.configure import natlinkconfigfunctions
  File "C:\Python\Python310-32\lib\site-packages\natlinkcore\configure\natlinkconfigfunctions.py", line 31, in <module>
    from natlinkcore import tkinter_dialogs
  File "C:\Python\Python310-32\lib\site-packages\natlinkcore\tkinter_dialogs.py", line 18, in <module>
    from tkinter import filedialog
ModuleNotFoundError: No module named 'tkinter'
```
When I run natlinkconfig_gui.exe, nothing happens.

**Comment by Voxellence** [comment]
Thanks, @LexiconCode. I was resisting the idea of letting NatLink install Python because I have my own preferred location. So after a quick Google I discovered that there's a checkbox, "tcl/tk and IDLE" which is required to install tkinter. Therefore, I simply ran the installer again, chose Modify, and checked the checkbox. Bada boom, the configuration programs now work.

This does remind me of an annoyance with the configuration utility that I've been meaning to address though, and maybe it's best to just mention it here rather than creating another issue.

The [documentation](https://natlink.readthedocs.io/en/latest/configure.html)  
says the `.natlink` directory is by default under the $HOME directory.  
However, it doesn't actually query the $HOME environment variable. Instead it assumes that we have left $HOME at its default Windows location, but in my case I have indeed changed it entirely.  

I've managed to change the location of the `.natlink` directory by creating and setting a new environment variable...  
`$NATLINK_USERDIR`  

We can use the Windows `Environment Variables` dialog box to add a `New...` User variable like...  
Variable name: NATLINK_USERDIR  
Variable value: %HOME%\.natlink  

That way it still has the same name but is now actually under $HOME as originally intended.

**Comment by dougransom** [comment]
How do we prevent users from running into this?

**Comment by quintijn** [comment]
Aaron, do you have a place to make this note??? Close this for now
