### ISSUE TITLE
test problem with natlinktimer.py

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/natlinkcore#69]
When running test_natlinktimer.py (from natlinkcore/tests) (or alltests.py), the following exception is thrown:

```
Exception ignored in: <function NatlinkTimer.__del__ at 0x044CBA48>
Traceback (most recent call last):
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\natlinktimer.py", line 97, in __del__
  File "C:\DT\NatlinkcoreDoug\src\natlinkcore\natlinktimer.py", line 284, in stopTimer
natlink.NatError: Calling setTimerCallback is not allowed before calling natConnect

```
It is not clear why. The natlinktimer module seems to run well. 

More intricate tests have been commented out. Maybe need a check too.

**Comment by quintijn** [comment]
Doug, something wrong with the tests in natlinkcore. Could you have a look or can we discuss this?

**Comment by quintijn** [comment]
let us forget about this for the moment...
