### ISSUE TITLE
documentation with sphinx does not seem to run with 32 bit version of python

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/natlinkcore#85]
I tried to start (again) the documentation of natlinkcore, by following the instructions on natlinkcore.readthedocs.io. 

However, after `pip install -r requirements.txt`, The script `make.bat html` does not seem to run.

I tried to install sphinx on a 64 bit python, but then I run into the complication that natlink is not recognised.

What to do?

**Comment by quintijn** [comment]
I thought of mocking 'natlink' in mock_modules, but another error:

`PS C:\dt\natlinkcoreDoug\documentation> ./make html
Running Sphinx v7.4.7
src_directory: C:\DT\natlinkcoreDoug\src\natlinkcore
sys.path:
['C:\\DT\\natlinkcoreDoug\\src\\natlinkcore', (...)]
====================

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\sphinx\config.py", line 529, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\DT\natlinkcoreDoug\documentation\conf.py", line 23, in <module>
    import natlinkcore
ModuleNotFoundError: No module named 'natlinkcore'
`

Any ideas???

`

**Comment by drmfinlay** [comment]
Hi Quintijn.  Please change line 18 of documentation\conf.py to the following:

	src_directory = os.path.join(os.path.abspath('..'), 'src')

That should allow 'natlinkcore' to be imported.

**Comment by quintijn** [comment]
Thank you, Dane. So stupid! 

Do you think sphinx indeed only runs on 64bit python? (I could try again on my 32bit python)

**Comment by quintijn** [comment]
OK then, there I go. It now runs on a 64bit python. But presenting problems still.

Dane, could you connect to the fork I am running on and see what result you get? When you have some time. I will give you the details via Telegram. Thanks already.

Greetings, Quintijn

**Comment by drmfinlay** [comment]
The docs should be buildable with 32-bit or 64-bit.

I'm not sure what fork you're using.  I was able to build the docs on the main branch by adding 'natlink', 'pydebugstring' and 'debugpy' to the `mock_modules` list in the conf.py file.  I also had to fix a syntax error in the modules.rst file.

**Comment by quintijn** [comment]
Dane, I do it with a 64 bit python, succeeded a bit, with natlinkutils.py (documentation from Joel Gould, 24 or 25 years ago!).

Please have a look (in master of natlinkcore), for example at the bottom of the playString documentation. I don't know exactly what I was doing.

Will proceed later.

**Comment by dougransom** [comment]
I too had trouble in 32 bit:
`C:\Users\doug\code\dt\unimacro\documentation>make.bat html
Running Sphinx v8.0.2
['C:\\Users\\doug\\code\\dt\\unimacro\\src', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\Scripts\\sphinx-build.exe', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\python310.zip', 'C:\\Program Files (x86)\\Natlink\\site-packages', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\DLLs', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib\\site-packages', 'C:\\Users\\doug\\code\\ft\\src', 'C:\\Users\\doug\\code\\dt\\pydebugstring\\src', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib\\site-packages\\win32', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib\\site-packages\\win32\\lib', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib\\site-packages\\Pythonwin', 'C:\\Users\\doug\\code\\dt\\unimacro\\src', 'C:\\Users\\doug\\code\\dt\\Vocola2\\src']
====================
unimacro, version: "4.1", release: "4.1.6"
loading translations [en]... done

Extension error:
Could not import extension sphinxcontrib.applehelp (exception: cannot import name 'SkipProgressMessage' from 'sphinx.util' (C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\sphinx\util\__init__.py))

C:\Users\doug\code\dt\unimacro\documentation>


Is there something else I might need to install?`

I have not tried 64 bit yet as I have to set up the environment.

**Comment by drmfinlay** [comment]
Quintijn, I think I've fixed the problem on the 'main' branch of natlinkcore.  RTD is now building and serving the current version at https://natlinkcore.readthedocs.io/en/latest/index.html.  Make sure to do a 'git pull'.

Doug, that error looks to be unimacro-related; I am using a 32-bit installation (Py 3.8) to build the natlinkcore docs without issue.

On Mon, 26 Aug 2024 08:13:18 -0700
Doug Ransom ***@***.***> wrote:

> I too had trouble in 32 bit:
> `C:\Users\doug\code\dt\unimacro\documentation>make.bat html
> Running Sphinx v8.0.2
> ['C:\\Users\\doug\\code\\dt\\unimacro\\src', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\Scripts\\sphinx-build.exe', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\python310.zip', 'C:\\Program Files (x86)\\Natlink\\site-packages', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\DLLs', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib\\site-packages', 'C:\\Users\\doug\\code\\ft\\src', 'C:\\Users\\doug\\code\\dt\\pydebugstring\\src', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib\\site-packages\\win32', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib\\site-packages\\win32\\lib', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib\\site-packages\\Pythonwin', 'C:\\Users\\doug\\code\\dt\\unimacro\\src', 'C:\\Us
 ers\\doug\\code\\dt\\Vocola2\\src']

**Comment by quintijn** [comment]
Great! Can I copy things to dtactions and to unimacro, or could youdo so? I will try later today.

Thanks, Quintijn 

Dane Finlay ***@***.***> schreef op 27 augustus 2024 10:23:21 CEST:
>Quintijn, I think I've fixed the problem on the 'main' branch of natlinkcore.  RTD is now building and serving the current version at https://natlinkcore.readthedocs.io/en/latest/index.html.  Make sure to do a 'git pull'.
>
>Doug, that error looks to be unimacro-related; I am using a 32-bit installation (Py 3.8) to build the natlinkcore docs without issue.
>
>On Mon, 26 Aug 2024 08:13:18 -0700

**Comment by drmfinlay** [comment]
Quintijn,

My apologies for taking so long to move on this!  The natlinkcore build is still failing at present, due to the package's natlink requirement.  This requirement cannot be installed on the RTD environment.  I will see what can be done about that.

In the meantime, I have added the required yaml file to the dtactions repository.  An error is preventing the automatic documentation of dtaction classes, however.  I will try to have a look into that and into Unimacro's documentation soon.

On Tue, 27 Aug 2024 01:26:56 -0700
Quintijn Hoogenboom ***@***.***> wrote:

> Great! Can I copy things to dtactions and to unimacro, or could youdo so? I will try later today.
> 
> Thanks, Quintijn 
> 
> Dane Finlay ***@***.***> schreef op 27 augustus 2024 10:23:21 CEST:
> >Quintijn, I think I've fixed the problem on the 'main' branch of natlinkcore.  RTD is now building and serving the current version at https://natlinkcore.readthedocs.io/en/latest/index.html.  Make sure to do a 'git pull'.
> >
> >Doug, that error looks to be unimacro-related; I am using a 32-bit installation (Py 3.8) to build the natlinkcore docs without issue.
> >
> >On Mon, 26 Aug 2024 08:13:18 -0700
> >Doug Ransom ***@***.***> wrote:
> >
> >> I too had trouble in 32 bit:
> >> `C:\Users\doug\code\dt\unimacro\documentation>make.bat html
> >> Running Sphinx v8.0.2
> >> ['C:\\Users\\doug\\code\\dt\\unimacro\\src', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\Scripts\\sphinx-build.exe', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\python310.zip', 'C:\\Program Files (x86)\\Natlink\\site-packages', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\DLLs', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib\\site-packages', 'C:\\Users\\doug\\code\\ft\\src', 'C:\\Users\\doug\\code\\dt\\pydebugstring\\src', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib\\site-packages\\win32', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib\\site-packages\\win32\\lib', 'C:\\Users\\doug\\AppData\\Local\\Programs\\Python\\Python310-32\\lib\\site-packages\\Pythonwin', 'C:\\Users\\doug\\code\\dt\\unimacro\\src', 'C:\
 \Us

**Comment by quintijn** [comment]
works with 64-bit python, so solved.
